export const feedbackActionTypes = {
  FEEDBACK_LIST_REQUEST: "FEEDBACK_LIST_REQUEST",
  FEEDBACK_LIST_SUCCESS: "FEEDBACK_LIST_SUCCESS",
  FEEDBACK_LIST_FAILURE: "FEEDBACK_LIST_FAILURE",

  POST_FEEDBACK_REQUEST: "POST_FEEDBACK_REQUEST",
  POST_FEEDBACK_SUCCESS: "POST_FEEDBACK_SUCCESS",
  POST_FEEDBACK_FAILURE: "POST_FEEDBACK_FAILURE",

  UPDATE_FEEDBACK_REQUEST: "UPDATE_FEEDBACK_REQUEST",
  UPDATE_FEEDBACK_SUCCESS: "UPDATE_FEEDBACK_SUCCESS",
  UPDATE_FEEDBACK_FAILURE: "UPDATE_FEEDBACK_FAILURE",

  DELETE_FEEDBACK_REQUEST: "DELETE_FEEDBACK_REQUEST",
  DELETE_FEEDBACK_SUCCESS: "DELETE_FEEDBACK_SUCCESS",
  DELETE_FEEDBACK_FAILURE: "DELETE_FEEDBACK_FAILURE",

};
